### ISSUE TITLE
Documentation request - add why?

### ISSUE THREAD

**Issue by RichardJECooke** [gabaroar/hapi-cors#1]
Why does this package exist? Doesn't hapi already have cors? It says it does in the documentation. I'm new to hapi, so I'm not sure if the normal cors stuff works correctly.

**Comment by gabaroar** [comment]
At the time there was issues with Hapi handling options headers causing cors requests to be blocked.  I would need to test if this is still the case.

**Comment by gabaroar** [comment]
I tested and it looks like the issues I was experiencing that led to this package no long exists in hapi core.  The below code will do the same thing as my example in the readme doc.

```
var Hapi = require("hapi");
var server = new Hapi.Server();

server.connection({
  port: 8080,
  routes: {
    cors: {
      origin: ['http://localhost:4200']
    }
  }
});

server.route({
  method: "GET",
  path: "/items",
  handler: function(request, reply){
    return reply({
      items: [
        {id: 1, name: "thing 1"},
        {id: 2, name: "thing 2"}
      ]
    });
  }
})

server.start(function(){
  console.log(server.info.uri);
});
```
